### ISSUE TITLE
Форма входа в модальном окне

### ISSUE THREAD

**Issue by i-ka** [i-ka/alchemy#18]

**Comment by VChet** [comment]
Форма регистрации тоже будет в модальном окне?

**Comment by i-ka** [comment]
Нужно отправлять запрос на новый view для логина(пока что new-login). Регистрация тоже в модальном окне?

**Comment by VChet** [comment]
Да

**Comment by i-ka** [comment]
Про это я не думал, придется еще и регистрацию немного переделать)

**Comment by i-ka** [comment]
57c058cb6bc642a3786de2c5b225e6310495bb02
