### ISSUE TITLE
Интерфейс игры 

### ISSUE THREAD

**Issue by i-ka** [i-ka/alchemy#20]
Предложения?

**Comment by VChet** [comment]
Есть какие-либо предложения?

**Comment by i-ka** [comment]
Надо бы какой-нибудь эффект при попытке смешивания, чтоб было видно, что не получилось смешать элементы, ну и при удачном смешивании тоже

## 

7aa590531c38875e86a43adfc7aef132050119d2

**Comment by VChet** [comment]
Предлагаю где-нибудь отображать результат смешивания. Что-то вроде:
название1 + название1 => нет результата
название1 + название2 => название3

**Comment by i-ka** [comment]
При удачном смешивании было бы неплохо

## 

afa9c0f074cc925c372e00c2e952b19674338caa

**Comment by i-ka** [comment]
я думал, это будет окошко которое на пару секунд появляется))

**Comment by VChet** [comment]
Так будет много времени отнимать, чтобы на каждый открытый элемент нужно было ждать, пока окно пропадет или кликать по нему.

**Comment by i-ka** [comment]
Не обязательно окно, которое все блокирует, можно даже строку, которая сверху появляться будет. Только для нее нужно место предусмотреть, чтоб шаблон не ездил туда-сюда. А так я минуты две искал ее:D

**Comment by VChet** [comment]
В том и дело, что если сверху добавлять, то игровое поле станет еще меньше, процентов на 10. Из возможных вариантов добавлять куда-нибудь в шапку по центру или что-то менять в шаблоне и убирать container, чтобы была возможность использовать края слева и справа от игрового поля. Всплывающие оповещения без доп. плагинов, как понял не сделать. Поэтому был оставлен такой вариант.
