### ISSUE TITLE
При смешивании элементов отправляется неверный запрос.

### ISSUE THREAD

**Issue by i-ka** [i-ka/alchemy#23]
1. Смешиваем 2 элемента и получаем результат (1+2 => 3)
2. Достаем еще один элемент, такой же что получился в 1
3. Смешиваем их (они не смешиваются, все ок) (3+3 => failed)
4. Повторяем шаг 1
5. Получаем success: false, в запросе отправляется 3+3(должно быть 1+2)

**Comment by VChet** [comment]
Проверить после 7aa590531c38875e86a43adfc7aef132050119d2
