### ISSUE TITLE
Страница ошибки при создании элемента

### ISSUE THREAD

**Issue by VChet** [i-ka/alchemy#25]
Происходит, если не были выбраны элементы для рецепта и элемент не выбран как исходный. Если точнее, то из-за [отсутствия value](https://github.com/i-ka/alchemy/blob/master/static/js/obj_drop.js#L2). Проверять присутствие атрибута перед отправкой формы, если его нет - выводить ошибку.

Еще один вариант делать значение равным 0, убрать сheckbox и закрашивать ячейки, как неактивные, если в них ничего не добавлено.
![](https://pp.vk.me/c631716/v631716106/423fc/WdxOzhnJLKQ.jpg)

**Comment by i-ka** [comment]
Это лучше на бекенде пофиксить

**Comment by i-ka** [comment]
1c228628cc1881676b7fd94ca34844f5133dc938
