### ISSUE TITLE
При смешивании 2 иконки элемента превращаются в результат

### ISSUE THREAD

**Issue by i-ka** [i-ka/alchemy#26]
Есть рецепт 1+2 =>3 
Достаем два элемента 1
Ставим их так, чтобы накладывались друг на друга
Кидаем на них элемент 2 (на то место, где они пересекаются)
Оба элемента 1 превращаются в 3

**Comment by VChet** [comment]
Не баг, а фича?

Как к первому `id1` добавился `id2`, так и ко второму `id1` добавился `id2`. Смешивание произошло - получился элемент. Да, он добавился в пропорциях не 1 к 1, но это уже условность, так почему бы так и не оставить?

**Comment by i-ka** [comment]
Просто, на мой взгляд странно, но не критично
