### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by i-ka** [i-ka/alchemy#34]
- [x] Модель отзыва
- [x] Передавать список отзывов в шаблон
- [x] Форма для отправки отзыва пользователем
- [x] Страница с подробностями отзыва
- [x] Удаление отзыва
- [x] Удаление старых скриншотов

**Comment by VChet** [comment]
https://github.com/i-ka/alchemy/compare/57f8a5f51f...7bd44a8297
