### ISSUE TITLE
Отдельная страница для игры

### ISSUE THREAD

**Issue by VChet** [i-ka/alchemy#39]
- [x] Перенести игру на отдельную страницу
- [x] Добавить в меню пункт "игра"

**Comment by i-ka** [comment]
Предлагаю всегда на индексе отображать лендинг, а в меню добавить ссылку на игру

## 

Ок

**Comment by VChet** [comment]
513da55aff4324af218075960411011a57ccec02...af133ba477a7b90ea8785c07108186b9c39b3c5d
